### ISSUE TITLE
Route helpers generating wrong path

### ISSUE THREAD

**Issue by arturictus** [basecamp/audits1984#40]
Hi,
Route helpers are generating paths to assets with params instead of the expected path.

 
<img width="922" alt="Pasted image 20230131170629" src="https://user-images.githubusercontent.com/1930175/215833597-1da1650b-8619-41c7-bc39-11dd4c68b7d5.png">

Debugging I get the same result:

```
[1, 10] in /audits1984/app/views/audits1984/sessions/_session.html.erb
    1: <%= link_to session_path(session) do %>
    2:   <% debugger %>
=>  3:   <article class="session media">
    4:     <div class="media-left">
    5:       <%= format_date session.created_at %>
    6:     </div>
    7:     <div class="media-content">
    8:       <div class="content">
    9:         <p>
   10:           <strong class="session__reason"><%= session.reason %></strong>
```
```ruby
session_path(session)
"/console/assets?action=show&controller=audits1984%2Fsessions&id=1"
```

When I copy the routes into my routes instead of mounting the engine it generates the correct routes:

```diff
- mount Audits1984::Engine => "/console"
+ namespace :audits1984, path: "console" do
+   resources :sessions, only: %i[index show] do
+     resources :audits, only: %i[create update]
+   end
+ 
+   resource :filtered_sessions, only: %i[update]
+ 
+   root to: "sessions#index"
+ end
```

I have other engines mounted in my router like:

- Sidekiq::Web
- JasmineRails::Engine
- LetterOpenerWeb::Engine
- GraphiQL::Rails::Engine

All of them are working perfectly

Using:

rails: 7.0.4
ruby: 3.2.0 (mri)
pg: 1.4.5
audits1984: 0.1.2
console1984: 0.1.26

**Comment by arturictus** [comment]
Continuing with the Path helpers errors.

When solving the first issue by copying the routes in the router instead of mounting.

In the controllers scope `sessions_path` is returning `"/sessions"` without the namespace, should be: `"/console/sessions"`

```ruby
[36, 45] in /audits1984/app/controllers/audits1984/audits_controller.rb
   36:         else
   37:           sessions_path
   38:         end
   39:
   40:         debugger
   41:
=> 42:         redirect_to next_path, notice: "Session #{@session.id} was #{@audit.status}"
   43:       end
   44:   end
   45: end
(byebug) next_path
=> "/sessions"
```
In the view:

```ruby
[1, 10] in /audits1984/app/views/audits1984/sessions/_session.html.erb
    1: <%= link_to session_path(session) do %>
    2:   <article class="session media">
    3:    <% debugger %>
=>  4:     <div class="media-left">
    5:       <%= format_date session.created_at %>
    6:     </div>
    7:     <div class="media-content">
    8:       <div class="content">
    9:         <p>
   10:           <strong class="session__reason"><%= session.reason %></strong>
(byebug) sessions_path
"/console/sessions"
```

**Comment by nikokon** [comment]
@arturictus was experiencing the same issue and came across https://github.com/rails/rails/issues/34452

I realized that we were including Rails.application.routes.url_helpers in our main app.
removing this resolves the issue.

adding include Audits1984::Engine.routes.url_helpers to Audits1984::ApplicationHelper also resolves the issue.

Haven't spend any more time diagnosing this but might as well make a note of this if someone elses encounters this issue

**Comment by northeastprince** [comment]
@jorgemanrubia how do you handle the audit routes in an application like Basecamp that has account ID middleware? Does it always require an account ID in the route but then it doesn't matter which account it is as long as the user is an admin? I have a similar setup and I'm getting `UrlGenerationError`s in a `before_action` callback in the base controller for redirecting if there's no current user, saying it can't find the sign in route with the given controller and action parameters even though it's resolving the path helper (and it works everywhere else in the app, just not when a controller from this engine is the one inheriting from the base controller).
